// Generated by Maravian Sockets CLI

declare namespace MSocketGenerated {

  interface Topics {

    "chat.messages": {
      publish: { "send": { "username": string; "text": string } };
      subscribe: { "send": { "username": string; "text": string } };
    }
    "system.presence": {
      publish: { "user.join": { "username": string }; "user.leave": { "username": string } };
      subscribe: { "user.join": { "username": string }; "user.leave": { "username": string } };
    }
  }

  type TopicName = keyof Topics;

  type PublishType<T extends TopicName> = keyof Topics[T]['publish'];

  type SubscribeType<T extends TopicName> = keyof Topics[T]['subscribe'];

  type PublishPayload<T extends TopicName, K extends PublishType<T>> = Topics[T]['publish'][K];

  type SubscribePayload<T extends TopicName, K extends SubscribeType<T>> = Topics[T]['subscribe'][K];

  type IncomingMessage<P> = { type: string; payload: P; ts?: number };

}
