// Auto-generated by docs-build.js
export const DOCS_VERSIONS = {
  "current": "0.5.0",
  "latest": "0.5.0",
  "versions": [
    {
      "version": "0.5.0",
      "path": "/api/v0.5.0",
      "label": "v0.5.0",
      "isLatest": true,
      "isStable": true,
      "releaseDate": null
    }
  ],
  "count": 1,
  "generatedAt": "2025-09-02T12:25:06.885Z"
};

export type DocsVersion = {
  version: string;
  path: string;
  label: string;
  isLatest: boolean;
  isStable: boolean;
  releaseDate: string | null;
};

export interface DocsVersionMetadata {
  current: string;
  latest: string;
  versions: DocsVersion[];
  count: number;
  generatedAt: string;
}

export const getCurrentVersion = () => DOCS_VERSIONS.current;
export const getAllVersions = (): DocsVersion[] => DOCS_VERSIONS.versions;
export const getLatestVersion = (): DocsVersion | undefined => 
  DOCS_VERSIONS.versions.find(v => v.isLatest);
