// Generated by Maravian Sockets CLI

declare namespace SocketMaxGenerated {

  interface Topics {

    "chat.messages": {
      publish: { "send": { "text": string } };
      subscribe: { "received": { "text": string; "from": string } };
    }
  }

  type TopicName = keyof Topics;

  type PublishType<T extends TopicName> = keyof Topics[T]['publish'];

  type SubscribeType<T extends TopicName> = keyof Topics[T]['subscribe'];

}
